{
 "title": "Payment Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Time Payments Retrieved",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(time_payments_retrieved_sum[2m]) / rate(time_payments_retrieved_count[2m])"
    }
   ]
  },
  {
   "title": "Payments Retrieve",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count_payments_retrieved" }
   ]
  },
  {
   "title": "Time Payments Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(time_payments_received_sum[2m]) / rate(time_payments_received_count[2m])"
    }
   ]
  },
  {
   "title": "Payments Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count_payments_received" }
   ]
  },
  {
   "title": "Payment Received Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count_payments_received_errors" }
   ]
  }
 ]
}